### ISSUE TITLE
Dev Container - Automatic Updates

### ISSUE THREAD

**Issue by asergeant01** [TelmoAndrade/vscode-vault#6]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
The ability to define inside a project `.devcontainer` folder a set of secrets that should be accessed from vault and inserted into the devcontainer when the container runs.

example format of secret definition file

```
vault_secrets:
- vaultConfiguration: '<Reference to vault defined in settings>'
   path: 'kv/ci/github'
  secretValues: 
  - envVar: 'GIT_USERNAME'
    vaultKey: 'service_username'
  - envVar: 'GIT_PASSWORD'
    vaultKey: 'service_password'
- vaultConfiguration: '<Reference to vault defined in settings>'
   path: 'kv/ci/artifactory'
   secretValues: 
  - envVar: 'ARTIFACTORY_API_KEY'
    vaultKey: 'API_TOKEN'
  - envVar: 'ARTIFACTORY_USER'
    vaultKey: 'USERNAME'
```

This would allow updates to secrets in vault to be automatically loaded into a devcontainer by simply restarting it.
It also allows developers to add new secrets and have those automatically available to other developers upon pull and restart.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
